import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/Providers/AuthProvider";
import { ThemeProvider } from "@/Providers/ThemeProvider";
import Navbar from "@/components/Nav/Navbar";
import ModalProvider from "@/components/Modals/ModalProvider";
import { Toaster } from "@/components/ui/toaster";
import EdgeStoreProvider from "@/Providers/EdgeStoreProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <AuthProvider>
        <body className={inter.className}>
          <EdgeStoreProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Navbar />
              <ModalProvider />
              {children}
              <Toaster />
            </ThemeProvider>
          </EdgeStoreProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
